version: "3.1"

services:
  xaibot:
    build: .
    container_name: "xaibot"
    restart: unless-stopped
    volumes:
      - ./src:/app
    environment:
      - TZ=Europe/Paris
      - LOGLEVEL=${LOGLEVEL:-INFO}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}
      - TELEGRAM_ALLOWED_GROUPS=${TELEGRAM_ALLOWED_GROUPS}
      - MISTRALAI_API_KEY=${MISTRALAI_API_KEY}

    